jobs:
  greeting:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/first-interaction@v1
      with:
        issue-message: '[Auto response] Looks like this is your first issue. I will
          look into it as soon as possible.'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Greetings
on:
  repository_dispatch:
    types: trigger-ga___greetings.yml
